### ISSUE TITLE
When would u release pretext training code?

### ISSUE THREAD

**Issue by TyroneLi** [xieenze/DetCo#1]

**Comment by xieenze** [comment]
After paper accepted :)

**Comment by cecilia930426** [comment]
Now the paper has been accepted. So when will you release your training code?

**Comment by shuaizzZ** [comment]
Now the paper has been accepted. So when will you release your training code? +1

**Comment by xieenze** [comment]
Hi all,
I am very busy on my internship project recently(as well as finding fulltime job and other many things!),  so I hardly have time to clean the code and opensource. Please understand!
Maybe u guys need to wait for several months, when I am free i will publish it
